language: python
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - DJANGO="Django>=1.11,<2.0"
install:
  - pip install -e .
  - pip install $DJANGO
  - pip install -r requirements-travisci.txt
script:
  - python runtests.py
