language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install -e .
  - pip install $DJANGO
  - pip install -r requirements-travisci.txt
script:
  - python runtests.py
env:
  - DJANGO="Django==1.5.8"
  - DJANGO="Django==1.6.5"
  - DJANGO="Django==1.7"
  - DJANGO="Django==1.8"
